insert into cryptocurrency (id, currency_code, display_name, unscaled_value, scale)
values (1, 'BTC', 'Bitcoin', 1960681, 2),
       (2, 'ETH', 'Ethereum', 129988, 2),
       (3, 'USDT', 'Tether', 102, 2),
       (4, 'BNB', 'BNP', 269, 8);

insert into countrylocale (country_code, country,  locale)
values
('AF','Afghanistan', 'ps'),
('AL', 'Albania', 'alb'),
('DZ', 'Algeria', 'FR'),
('AD', 'Andorra',  'cat'),
('AO', 'Angola',  'chn'),
('AG', 'Antigua and Barbuda',  'en'),
('AR', 'Argentina',  'es'),
('AM', 'Armenia',  'arm'),
('AU',  'Australia', 'en'),
('AT',  'Austria', 'de'),
('AZ',  'Azerbaijan', 'rus'),
('BS', 'Bahamas',  'en'),
('BH',  'Bahrain', 'ara'),
('BD',  'Bangladesh', 'ben'),
('BB',  'Barbados', 'en'),
('BY',  'Belarus', 'rus'),
('BE',  'Belgium', 'fr'),
('BZ', 'Belize', 'en'),
('BJ', 'Benin',  'fr'),
('BT',  'Bhutan','dz'),
('BO',  'Bolivia', 'es'),
('BA', 'BOSNIA AND HERZEGOVINA',  'bs'),
('BW',  'BOTSWANA', 'en'),
('BV', 'BOUVET ISLAND',  'no'),
('BR', 'BRAZIL', 'pt'),
('IO', 'BRITISH INDIAN OCEAN TERRITORY',  'en'),
('BN', 'BRUNEI DARUSSALAM', 'ms'),
('BG', 'BULGARIA', 'bg'),
('BF', 'BURKINA FASO',  'fr'),
('BI', 'BURUNDI', 'fr'),
('KH', 'CAMBODIA', 'km'),
('CM','CAMEROON', 'fr'),
('CA', 'CANADA', 'en'),
('CV', 'CAPE VERDE','pt'),
('KY', 'CAYMAN ISLANDS', 'en'),
('CF', 'CENTRAL AFRICAN REPUBLIC', 'fr'),
('TD', 'CHAD', 'fr'),
('CL','CHILE', 'es'),
('CN', 'CHINA', 'zh'),
('CX', 'CHRISTMAS ISLAND', 'en'),
('CC', 'COCOS (KEELING) ISLANDS', 'ms'),
('CO', 'COLOMBIA',  'es'),
('KM',  'COMOROS', 'fr'),
( 'CG', 'CONGO', 'fr'),
('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE',  'fr'),
('CK', 'COOK ISLANDS', 'en'),
('CR', 'COSTA RICA', 'es'),
('CI',  'CÔTE D''IVOIRE', 'fr'),
('HR', 'CROATIA', 'hr'),
('CU',  'CUBA', 'es'),
('CY',  'CYPRUS', 'el'),
('CZ',  'CZECH REPUBLIC', 'cs'),
('DK', 'DENMARK', 'da'),
('DJ', 'DJIBOUTI', 'fr'),
('DM', 'DOMINICA',  'en'),
( 'DO', 'DOMINICAN REPUBLIC', 'es'),
('EC', 'ECUADOR',  'es'),
('EG', 'EGYPT',  'ar'),
('SV',  'EL SALVADOR', 'es'),
( 'GQ', 'EQUATORIAL GUINEA', 'es'),
('ER', 'ERITREA',  'ti'),
('EE', 'ESTONIA',  'et'),
('ET','ETHIOPIA',  'am'),
('FK', 'FALKLAND ISLANDS (MALVINAS)',  'en'),
('FO', 'FAROE ISLANDS',  'fo'),
('FJ', 'FIJI', 'fj'),
('FI', 'FINLAND', 'fi'),
('FR', 'FRANCE', 'fr'),
('GF', 'FRENCH GUIANA', 'fr'),
('PF', 'FRENCH POLYNESIA',  'fr'),
('TF', 'FRENCH SOUTHERN TERRITORIES',  'fr'),
('GA', 'GABON', 'fr'),
('GM', 'GAMBIA', 'en'),
('GE',  'GEORGIA', 'ka'),
('DE', 'GERMANY', 'de'),
('GH', 'GHANA',  'fr'),
('GI', 'GIBRALTAR', 'en'),
('GR', 'GREECE', 'el'),
('GB', 'UNITED KINGDOM',  'en'),
('US', 'UNITED STATES',  'en')
--TODO list incomplete
;